version: '3.4'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=smolltolk_chat_prod
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./chat-data:/var/lib/mysql

  chat:
    image: smolltolk/chat
    environment:
      - PORT=4000
      - DATABASE_URL=ecto://root:root@db/smolltolk_chat_prod
    ports:
      - 4000:4000
    depends_on:
      - db
    links:
      - db

  client:
    image: smolltolk/client
    ports:
      - 9000:80
    links:
      - chat
      - cloudsync
    depends_on:
      - chat
      - cloudsync

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data

  cloudsync:
    image: miroslavlalev/cloudsync
    volumes:
      - ./repo:/repo
    ports:
      - 80:8080
    links:
      - redis
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REPO=/repo
      - REDIS_URL=redis:6379
