version: '3'
services:
    db:
        image: mysql
        environment:
            - MYSQL_DATABASE=smolltolk_chat_prod
            - MYSQL_ROOT_PASSWORD=root
    chat:
        image: local/chat:0.0.2
        environment:
            - PORT=4000
            - DATABASE_URL=ecto://root:root@db/smolltolk_chat_prod
        ports:
            - "4000:4000"
        depends_on:
            - db
